<?php

use App\Models\XrefPostcode;
use Eighty8\LaravelSeeder\Migration\MigratableSeeder;
use Eighty8\LaravelSeeder\Repository\DisableForeignKeysTrait;

class XrefPostcodePerlisSeeder extends MigratableSeeder
{
    use DisableForeignKeysTrait;

    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $data_seeds = [
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Jawi Matang' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Bintong' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Datuk Wan Ahmad' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Datuk Setia' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Datuk Jaafar Hassan' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Choo Kee' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Ceria' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Cergas' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Cahaya' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Bunga Raya' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Jawi Matang' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Bintong' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Datuk Wan Ahmad' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Datuk Setia' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Datuk Jaafar Hassan' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Choo Kee' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Ceria' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Cergas' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Cahaya' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Bunga Raya' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Bunga Kemboja RPA' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Bumita' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Bukit Kayangan' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Bukit Kaya' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Bintong Utama' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Bintong Setia' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Bintong Maju' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Behor Indah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Jarak' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Katong' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Jarak' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Jali' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Ira' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Intan' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Indera' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Idaman' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Hijrah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Guru Jaya' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Guru' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Gembira' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Gasing' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Firdaus' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Fauziah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Sentua' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Putra' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Pulai' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Desa Kayangan' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Bakau Emas' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Aman' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Abu Bakar Munir' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Ujung Bukit' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Sumbing' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Pong' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Peduka' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Larak' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Kembong' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Kandang' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Jepun' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Jawa' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Gong' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tok Dewa' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Titi Tok Bandar' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Titi Teras' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tengah Abi' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Temak' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telok Tui' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telok Kacang' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Utan Aji' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Utan Temak' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Sena Rendang' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Repoh' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Perumahan Awam Santan' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Perumahan Awam Bohor Lateh' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Pengkalan Asam' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Padang Bohor' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Mengkuang Layar' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Lukuk Gajah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Lorong Sekolah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Lorong Nisam' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Lorong Kampung Sena' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Lorong Haji Seman' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kubang Arang' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kangar' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Wang Ulu' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Wang Besar' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Wang Belimbing' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telok Jambu' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Ujung Batu' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Pilihan' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Murni' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Medan' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Manis' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Intan' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Idaman' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Embun' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Bahagia' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Sepadu 1' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Sepadu' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Sentua' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Sena Permai' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Sena Indah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Sena' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Repoh Jaya' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Repoh Indah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Repoh' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Puchong' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Pulai 4' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Tok Peduka' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Titi Midin' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Titi Chai'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Wira' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Utara' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Utama Indah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Utama' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Tok Peduka' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Teratai' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Ten' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Syed Alwi' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Suriani' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Sri Guar Syed Alwi' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Simpang Tiga' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Setia Utama' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Seriab' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Seri Tanjung' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Rasa Sayang' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Putra Putri' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Putera' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Mas Putra' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Mas Muda' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Mada Sepakat' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Lima Naleh' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Lewata' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Koperasi' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Kenanga' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Kemajuan' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Kecor Indah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Kechor Jaya' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Kechor Indah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Kayangan Indah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Kastam' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Kangar' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Jelati' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Jejawi' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Jaya Diri' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Mas Ria' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Medan Sepakat' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Pertiwi Seriab' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Pertiwi Indah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Pertama' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Permai' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Perlis' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Pengkalan Indah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Pengkalan Assam' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Pekeliling' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Peduka' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Norma' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Mutiara' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Murni' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Muda Sepakat' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Mewah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Mesra Jejawi' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Mesra' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Merpati' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Taman Jaya' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bukit Kecil' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Cicar' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Batu Pahat' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Batu 3.5 (Jalan Kaki Bukit)' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Baru Santan' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Baru' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Baroh' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bakong (Jejawi)' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bakau' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Aur' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Asam 6' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Aman' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Sena' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Redeh' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Pulai' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Marus' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Lanchang' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Kabong' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Empiang' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Inai' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bukit Besi Hangit' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bohor Temak' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bohor Inai' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bohor Goncar' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bohor Gelam' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bohor Gandil' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bohor Chichar' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bintong' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Binjal' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bendang Baru' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Belukar (Kangar)' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Belat Santan' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Belangga Pudak' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Temak' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Pulai' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Kebal' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Behor Janggus' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Dalam' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor Ara' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Alor' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Medan Kangar' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Masjid Lama' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Kurung Batang' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Kangar' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Kampung Wan Abdullah' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Kaki Bukit (Batu 4 1/2)' ],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Jubli Perak'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Hospital'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Home Guard'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Bukit Meranti'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Bohor Guncar'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Besar Kangar'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Arau'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Alor Sena'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Abi Tok Hashim'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Bohor Gelam'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Alor Tok Terang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Padang Bohor'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Panglima'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Abi Tok Hashim'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Abi Pokok Asam'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Abi Padang Machang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Abi Batas Paip'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jejawi'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Tun Razak'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Tok Kandang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Teluk Kacang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Taman Bunga Padi'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Syed Omar'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Seruling'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Santan (Km 5)'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Raja Syed Saffi'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Raja Syed Alwi'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Raja Muda'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Penjara'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Jalan Pegawai'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Alor Redeh'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telok Gelam'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sempering'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Santan Masjid'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Santan Enam'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Santan Belat'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Santan Aur'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Santan'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Salang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Repoh Dagang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Repoh'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Pulau'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Pondok'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Pokok Jawi'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Petai Hilir'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Petai'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Peseri'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Pengkalan Asam'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Penghulu Bakar'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sena'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sena Sematang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telok Epa'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telaga Nyiur Manis'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Telaga Idi'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tebing Tinggi'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tanjung Sila'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tanjung Gorah'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tanjung Buluh'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Tanjung'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Syed Umar'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Surau'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sungai Siran'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sungai Santan'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sungai Baru'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sungai Bakong'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Seriab'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sentua'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Sentang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Parit Jari'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Panggau'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Bunga Pudak'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kota Keran'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kota'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Keranji'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kechor'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Jejawi Sematang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Jejawi Dalam'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Jarak'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Hutan Melintang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Hutan Buluh'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Haji Daud'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Guru'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Gunong'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Guar Ujung Batu'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Guar Syed Alwi'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Datuk'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Dasri'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Dagang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kota Ulu'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kubang Arang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Jawa Seriab'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Katong'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Kedepiang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Machang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Nyaring'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Pauh'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Petani'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Seberang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Padang Behor'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Nyak Adam'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kubang Badak'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kubang Cekuang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kubang Gajah'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Kurung Batang'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Lin'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Masjid (Kangar)'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Mengkuang Layar'],
            [ 'xref_state_id' => 9, 'code' => '01000', 'name' => 'Kampung Nissam'],
            [ 'xref_state_id' => 9, 'code' => '01007', 'name' => 'Kangar - Peti surat'],
            [ 'xref_state_id' => 9, 'code' => '01009', 'name' => 'Kangar - Beg berkunci'],
            [ 'xref_state_id' => 9, 'code' => '01500', 'name' => 'DYMM Tuanku Raja Perlis'],
            [ 'xref_state_id' => 9, 'code' => '01502', 'name' => 'YAB Menteri Besar Perlis'],
            [ 'xref_state_id' => 9, 'code' => '01503', 'name' => 'Setiausaha Kerajaan Negeri'],
            [ 'xref_state_id' => 9, 'code' => '01504', 'name' => 'Biro Bantuan Guaman'],
            [ 'xref_state_id' => 9, 'code' => '01505', 'name' => 'Biro Pengaduan Awam'],
            [ 'xref_state_id' => 9, 'code' => '01506', 'name' => 'Mahkamah Tinggi'],
            [ 'xref_state_id' => 9, 'code' => '01506', 'name' => 'Mahkamah Sesyen'],
            [ 'xref_state_id' => 9, 'code' => '01508', 'name' => 'Amanah Raya Berhad'],
            [ 'xref_state_id' => 9, 'code' => '01512', 'name' => 'Penasihat Undang-Undang Negeri'],
            [ 'xref_state_id' => 9, 'code' => '01514', 'name' => 'Jabatan Perangkaan'],
            [ 'xref_state_id' => 9, 'code' => '01516', 'name' => 'Jabatan Pemegang Harta'],
            [ 'xref_state_id' => 9, 'code' => '01517', 'name' => 'Jabatan Perpaduan Negara'],
            [ 'xref_state_id' => 9, 'code' => '01518', 'name' => 'Jabatan Audit Negeri'],
            [ 'xref_state_id' => 9, 'code' => '01524', 'name' => 'Setiausaha Keselamatan Negeri'],
            [ 'xref_state_id' => 9, 'code' => '01529', 'name' => 'Unit Penyelidikan Sosio Ekonomi'],
            [ 'xref_state_id' => 9, 'code' => '01532', 'name' => 'Jabatan Sumber Manusia'],
            [ 'xref_state_id' => 9, 'code' => '01538', 'name' => 'Jabatan Keselamatan Sosial (Perkeso)'],
            [ 'xref_state_id' => 9, 'code' => '01540', 'name' => 'Jabatan Tenaga Rakyat'],
            [ 'xref_state_id' => 9, 'code' => '01546', 'name' => 'Unit Pencegah Penyeludupan'],
            [ 'xref_state_id' => 9, 'code' => '01546', 'name' => 'Pejabat Rela Negeri'],
            [ 'xref_state_id' => 9, 'code' => '01550', 'name' => 'Jabatan Imigresen'],
            [ 'xref_state_id' => 9, 'code' => '01551', 'name' => 'Jabatan Pendaftaran Negara'],
            [ 'xref_state_id' => 9, 'code' => '01556', 'name' => 'Jabatan Pertahanan Awam'],
            [ 'xref_state_id' => 9, 'code' => '01560', 'name' => 'Ketua Polis Negeri'],
            [ 'xref_state_id' => 9, 'code' => '01564', 'name' => 'Jabatan Kebajikan Masyarakat'],
            [ 'xref_state_id' => 9, 'code' => '01570', 'name' => 'Jabatan Belia Dan Sukan'],
            [ 'xref_state_id' => 9, 'code' => '01572', 'name' => 'Perpustakaan Awam Negeri'],
            [ 'xref_state_id' => 9, 'code' => '01576', 'name' => 'Jabatan Tanah Dan Galian'],
            [ 'xref_state_id' => 9, 'code' => '01578', 'name' => 'Jabatan Ukur & Pemetaan'],
            [ 'xref_state_id' => 9, 'code' => '01582', 'name' => 'Jabatan Kerja Raya'],
            [ 'xref_state_id' => 9, 'code' => '01586', 'name' => 'Hospital Kangar'],
            [ 'xref_state_id' => 9, 'code' => '01590', 'name' => 'Jabatan Kesihatan'],
            [ 'xref_state_id' => 9, 'code' => '01592', 'name' => 'Pegawai Kewangan Negeri'],
            [ 'xref_state_id' => 9, 'code' => '01594', 'name' => 'Akauntan Negeri'],
            [ 'xref_state_id' => 9, 'code' => '01596', 'name' => 'Jabatan Kastam & Eksais Di Raja'],
            [ 'xref_state_id' => 9, 'code' => '01598', 'name' => 'Kumpulan Wang Simpanan Pekerja'],
            [ 'xref_state_id' => 9, 'code' => '01600', 'name' => 'Lembaga Hasil Dalam Negeri'],
            [ 'xref_state_id' => 9, 'code' => '01604', 'name' => 'Jabatan Pendidikan'],
            [ 'xref_state_id' => 9, 'code' => '01606', 'name' => 'Jabatan Kemajuan Masyarakat (Kemas)'],
            [ 'xref_state_id' => 9, 'code' => '01608', 'name' => 'Jabatan Pembangunan Koperasi'],
            [ 'xref_state_id' => 9, 'code' => '01609', 'name' => 'Pejabat Mara Negeri'],
            [ 'xref_state_id' => 9, 'code' => '01610', 'name' => 'Bahagian Perlesenan - Kementerian Penerangan'],
            [ 'xref_state_id' => 9, 'code' => '01612', 'name' => 'Jabatan Penerangan'],
            [ 'xref_state_id' => 9, 'code' => '01614', 'name' => 'Jabatan Penyiaran'],
            [ 'xref_state_id' => 9, 'code' => '01620', 'name' => 'Jabatan Pengangkutan Jalan'],
            [ 'xref_state_id' => 9, 'code' => '01622', 'name' => 'Unit Penguatkuasa Kem. Perdagangan & Perindustrian'],
            [ 'xref_state_id' => 9, 'code' => '01626', 'name' => 'Jabatan Pengairan Dan Saliran'],
            [ 'xref_state_id' => 9, 'code' => '01628', 'name' => 'Jabatan Perikanan'],
            [ 'xref_state_id' => 9, 'code' => '01630', 'name' => 'Jabatan Haiwan'],
            [ 'xref_state_id' => 9, 'code' => '01632', 'name' => 'Jabatan Pertanian'],
            [ 'xref_state_id' => 9, 'code' => '01634', 'name' => 'Panglima Markas 12 Briged'],
            [ 'xref_state_id' => 9, 'code' => '01644', 'name' => 'Majlis Perbandaran Kangar'],
            [ 'xref_state_id' => 9, 'code' => '01646', 'name' => 'Jabatan Perancang Bandar Dan Desa'],
            [ 'xref_state_id' => 9, 'code' => '01648', 'name' => 'Jabatan Bomba & Penyelamat'],
            [ 'xref_state_id' => 9, 'code' => '01660', 'name' => 'Jabatan Perhutanan'],
            [ 'xref_state_id' => 9, 'code' => '01664', 'name' => 'Jabatan Perhilitan'],
            [ 'xref_state_id' => 9, 'code' => '01670', 'name' => 'Pos Malaysia Berhad'],
            [ 'xref_state_id' => 9, 'code' => '01672', 'name' => 'Telekom Malaysia Berhad'],
            [ 'xref_state_id' => 9, 'code' => '01673', 'name' => 'Tenaga Nasional Berhad'],
            [ 'xref_state_id' => 9, 'code' => '01674', 'name' => 'Pegawai Kemajuan Negeri'],
            [ 'xref_state_id' => 9, 'code' => '01676', 'name' => 'Jabatan Agama Islam Perlis'],
            [ 'xref_state_id' => 9, 'code' => '01680', 'name' => 'Dewan Undangan Negeri'],
            [ 'xref_state_id' => 9, 'code' => '01694', 'name' => 'Jabatan Kebudayaan & Kesenian'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Tanjung Gelam'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Telok'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Tengah'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Tengah Bohor Lateh'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Terus Teritip'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Titi Serong'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Tok Kaya'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Tok Kuning'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Tandiap'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Sungai Mati'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Seberang Tok PI'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Peladang'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Perak'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Pokok Asam'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Puju'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Pulau'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Pulau Ketam'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Seberang Alor'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Seberang Jaya'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Utan Ibus'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Wai'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Taman Bukit Kubu'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Taman Indera Indah'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Taman Kuala Perlis'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Taman Peladang Jaya'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Taman Semarak'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Taman Sentosa'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Taman Seri Bayu'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Taman Seri Semarak'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Taman Berlian'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Sungai Siput'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Wang Pinang'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kawasan Perindustrian Kuala Perlis'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kuala Perlis'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Persiaran Putra Timur 1'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'PPRT Tok Kuning'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Rancangan Perumahan Awam 2 KPS'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Sungai Berembang'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Sungai Manor'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Taman Suria'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Pak Lengah'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Al Marhom Kayang'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Jalan Siakap'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Jalan Simpang Empat (Batu 3 3\/4 - 4 1\/2)'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bahagia'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bangsal Lebah'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Baru (Jalan Sarawak)'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Baru Jeti'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Baru Tandiap'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Baru Tok Kuning'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Jalan Serawak'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Jalan Panggong'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Bohor Lateh'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Bohor Mali'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Bukit Puteh'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Bukit Tok Po'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Jalan Besar'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Jalan Lama Kuala Perlis (Batu 4)'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Jalan Masjid'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Jalan Miri'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Batu Buaya'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Batu Lima'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Kota Kayang'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Kuala'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Kurung Tengar'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Langgar'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Nelayan'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Padang Besar Selatan'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Padang Cina'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Padang Jamil'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Kolam Raja'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Hujung Tanjung'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bukit Papan'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Behor Lateh'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Belakang Kilang'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Besar'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bohor Ibus'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bohor Lateh'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bohor Mesjid'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bohor Rotan Pahit'],
            [ 'xref_state_id' => 9, 'code' => '02000', 'name' => 'Kampung Bohor Tui'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Tok Wan Nik'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Titi Tinggi Ulu'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Titi Tinggi Hilir'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Titi Tinggi'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Tersusun (Batu 20)'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Syed Abdan'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Sungai Chuchuh'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Sena'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Sahabat'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kem Askar Rimba Mab'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Padang Besar'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Pusat Serenti Bukit Cabang'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Taman Singgah Sana'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Taman Perumahan Awam'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Taman Kim 2'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Taman Kim'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Taman Kastam Baru'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Taman Bunga Cina'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Taman Bunga Cempaka'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Sekolah Menengah Padang Besar'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Taman Utara Jaya (Fasa 1 - 3)'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Petani'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Bukit Cabang'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Alor Dalam (Bukit Chabang)'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Jalan Padang Besar (Km 19)'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Gapura Squre'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Gapura Square'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Felda Rimba Mas'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Felda Mata Ayer'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Felcra Lubuk Sireh'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Emas Kerajang'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Asmara'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Baru'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Baru Bukit Chabang'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Padang Mawa'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Melayu'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Masjid'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Kolam'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Kok Mak'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Guar Tinggi (Titi Tinggi)'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Chantek'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Bukit Chabang'],
            [ 'xref_state_id' => 9, 'code' => '02100', 'name' => 'Kampung Baru Jalan Sahabat'],
            [ 'xref_state_id' => 9, 'code' => '02200', 'name' => 'Taman Singgahsana'],
            [ 'xref_state_id' => 9, 'code' => '02200', 'name' => 'Kampung Wang Kelian'],
            [ 'xref_state_id' => 9, 'code' => '02200', 'name' => 'Kampung Tassoh'],
            [ 'xref_state_id' => 9, 'code' => '02200', 'name' => 'Kaki Bukit'],
            [ 'xref_state_id' => 9, 'code' => '02200', 'name' => 'Jalan Padang Besar (Batu 16)'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Sungai Buloh'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Sungai Jerneh'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Sungai Paya'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Sungai Serai'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Tanjong'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Titi Tampang'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Tunjong Beseri'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Wang Pisang'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Wang Tangga'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Wang Tengku Lembu'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kilang Gula'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Lembaga Pertubuhan Peladang'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Lembaga Tembakau Negara'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Lubuk Besar'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Sungai Baru Serai'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Songla'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Simpang 3 Panggas'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Padang Lati'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Padang Malau'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Padang Melangit'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Paya'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Paya Kelubi'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Paya Senduk'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Paya Ulu'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Penghulu Jaafar'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Perawah'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Raja Conggah'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Semadong'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Sena Rendang'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Simpang 3 Kilang Gula'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Padang Jelutong'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Maktab Rendah Sains Mara'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Beseri Indah'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Beseri Jaya'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Beseri Murni'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Beseri Paya'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Bunga Geti'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Che Long'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Dua Puluh'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Geti'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Has Melati'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Haz Melati'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Mas (Beseri)'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Melati Indah (Beseri)'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Permai'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Bahagia'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Angsana'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Sekolah Menengah semadung'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Padang lati'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Paya Batu 5'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Paya Besar'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Paya Pauh Gembol'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Paya Pauh Gembol'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Paya Senduk'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Paya Tengah'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Perumahan Kilang Gula'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Perumahan Perlis Plantation'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Pusat Haiwan Bukit Temiang'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'RPA Batu 8'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'RPA Bukit Keteri'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'RPA Chuping'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Taman Sempurna Jaya'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Beseri'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Alor Kangar'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Alor Tampang'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Balai Baru'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Baru Ngulang'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Baru Pangas'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Batu Bertangkup'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Batu Hampar (Beseri)'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Behor Kulit Kerang'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Behor Madi'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Belat Batu Beseri'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Belukar Lengga'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Beseri Dalam'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Beseri Jaya'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung  Semadung'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'JKR Bekalan Air Tassoh'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'JKR (bekalan air timah tasoh)'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Beseri Dalam'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Bilal Uduh'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Bohor Madi'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Bukit Keteri'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Empangan Timah Tassoh JPS'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Guar Panji'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Institut Kemahiran Mara'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Jabatan Pertanian Bukit Temiang'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Jalan Asam Paya'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Jalan Beseri - Bukit Keteri'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Jalan Kaki Bukit (Batu 4 3\/4 - 6 1\/4)'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Jalan padang melangit'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Jalan Santan (Batu 3 3\/4 - 5)'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bilal Uduh'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bohor Luar'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Kelang Beseri'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Kepala Batas Dato Kayaman'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Kubang Jeliti'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Kubang Tiga'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Kubang Tiga'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Lembah Biak'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Lubok Batu'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Lubok Gajah'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Lubok Hitam Manis'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Lubuk Machang'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Masjid Beseri'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Mempelas'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Ngulang'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Padang Gelam'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Guar Sanai'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Guar Medan Gatal'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bongkok'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Jernih'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Kedak'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Manek Barat'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Merah'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Merah Hilir'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Merah Hulu'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Merah Hulu'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Guar Jentek'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Datuk Sheikh Ahmad'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Darat Selatan'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Darat'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Chichak Terbelit'],
            [ 'xref_state_id' => 9, 'code' => '02400', 'name' => 'Kampung Bukit Temiang'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Kampung Padang Jelutong'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Kampung Paya Kelubi'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Kampung Perawah'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Kampung Songla'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Kampung Sungai Buloh'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Taman Tunjung'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Kampung Padang Gelam'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Kampung Masjid (Beseri)'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Bukit Keteri'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Guar Panji'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Kampung Belukar Lengga'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Kampung Bukit Jernih'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Kampung Kepala Batas Dato Kaya'],
            [ 'xref_state_id' => 9, 'code' => '02450', 'name' => 'Kampung Kubang Tiga'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Simpang Geti'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Saikla'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Pokok Sena'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Pokok Petai'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Perik'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Paya Burma'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Panggas Kechil'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Panggas Besar'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Panggas'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Padang Nyu'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Oran'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Sungai Mati'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kok Klang'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Lubuk Besar'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Taman Sri Idaman'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Taman Selasih'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Taman Ria'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Taman Permata'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Taman Padang Nyu'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Taman Mata Air (2 - 3)'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Taman Haji Ali (RPA)'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Stesen Meteorilogi'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Sekolah Jenis Kebangsaan Cina Kong Aik'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Pekan Gate Mata Air'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Mata Ayer'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Kubang Peron'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Kersek (Mata Ayer)'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Bukit Chuping'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Changkat Lada'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Bukit Chuping'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Belukar (Mata Ayer)'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Bawah Bukit'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Banggol Sena'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Balik Guar'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Balik Bukit Selatan'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Balik Bukit'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Jalan Mata Ayer (Km 1.6 - 6)'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Hutan Lembah'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Felda Chuping'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Che gu Ali'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Chelong'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Kersek (Kangar)'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Kerisik Hilir'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Hutan Temin'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Hutan Lembah'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Hutan Lembah'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Guar Nangka'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Guar Nangka'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Chuping'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Gial'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Gial Tengah'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Guar Halban'],
            [ 'xref_state_id' => 9, 'code' => '02500', 'name' => 'Kampung Guar Musang'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Telaga Haji Latif'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Tambun Tulang'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Stesen'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Sena'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Pulau Pichai'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Pida 3 Lama'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Pauh'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Paloh'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Padang Telela'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Telok'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Titi Besi'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Ulu Pauh'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'UiTM Arau'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Taman Utara Guar Sanji'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Taman Sri Pauh'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Taman Seri Wangi'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Taman Seri Idaman'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Taman Pauh Indah'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Taman Desa Pauh'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Rani Estate'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Pauh'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Padang Siding'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Padang Biak'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Arau'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Bohor Mengkung'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Belukar'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Belat Raja'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Belat Batu'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Batas Liku'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Banat'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Bakong (Arau)'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Alor Merah'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Guar Sanji'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Bohor Mentalun'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Changkat Jawi'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Kubang Siput'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Kubang Mat Tanggok'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Kuala Tunggang'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Katong'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Jelempok'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Hutan Kandis'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Guring'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Guar Gajah'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Chermai'],
            [ 'xref_state_id' => 9, 'code' => '02600', 'name' => 'Kampung Changkat Kabu'],
            [ 'xref_state_id' => 9, 'code' => '02607', 'name' => 'Arau - Peti surat'],
            [ 'xref_state_id' => 9, 'code' => '02609', 'name' => 'Arau - Beg berkunci'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Serdang'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Sematang Serdang'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Pulau'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Permatang Pauh'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Permatang Limau Manis'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Permatang Bongor'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Pauh Tiga Beradek'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Sungai Baru'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Sungai Belati'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Sungai Bugis'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Sungai Padang'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Tebuk'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Titi Beratap'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Tok Pulau'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Simpang Ampat'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Taman Cendera Wasih'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Taman Pelangi'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Padang Petani'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Padang Benta'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Mua'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Bohor Mali'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Banir Tembus'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Batas Lentang'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Bendang Baru'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Berjaya'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Bohor Lalang'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Bonggor Kudong'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Bunga Mas'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Chantek Bangun'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Che Ok'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Chemumar'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Jawi Endol'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Kenangan'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Lat Seribu'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Long Boh'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Matang Kersek'],
            [ 'xref_state_id' => 9, 'code' => '02700', 'name' => 'Kampung Melintang'],
            [ 'xref_state_id' => 9, 'code' => '02707', 'name' => 'Simpang Ampat - Peti surat'],
            [ 'xref_state_id' => 9, 'code' => '02709', 'name' => 'Simpang Ampat - Beg berkunci'],
            [ 'xref_state_id' => 9, 'code' => '02800', 'name' => 'Kampung Kepala Batas Pauh'],
            [ 'xref_state_id' => 9, 'code' => '02800', 'name' => 'Kampung Kerbau Belaga'],
            [ 'xref_state_id' => 9, 'code' => '02800', 'name' => 'Kampung Matang Keriang'],
            [ 'xref_state_id' => 9, 'code' => '02800', 'name' => 'Kampung Padang Gelam'],
            [ 'xref_state_id' => 9, 'code' => '02800', 'name' => 'Kampung Padang Keria'],
            [ 'xref_state_id' => 9, 'code' => '02800', 'name' => 'Kampung Permatang Pelangu'],
            [ 'xref_state_id' => 9, 'code' => '02800', 'name' => 'Kampung Rama'],
            [ 'xref_state_id' => 9, 'code' => '02800', 'name' => 'Kampung Simpang Sanglang'],
            [ 'xref_state_id' => 9, 'code' => '02800', 'name' => 'Kampung Tanah Timbul']
        ];

        foreach ($data_seeds as $seed) {
            XrefPostcode::create($seed);
        }
    }

    /**
     * Reverts the database seeder.
     */
    public function down(): void
    {
        // Remove your data
    }
}
